services:
  - type: web
    name: flowlytics-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        sync: false
